packages:
  - apps/*
  - clients/typescript/*
  - sdks/typescript

linkWorkspacePackages: true
preferWorkspacePackages: true

allowBuilds:
  esbuild: true
  workerd: true

onlyBuiltDependencies:
  - esbuild
  - workerd

nodeVersion: 24.13.0
