/**
 * Prepare the end-to-end Worker: a fresh throwaway relayer keypair in
 * `e2e/.dev.vars`, funded from the local Surfpool faucet, and a clean D1.
 * Run by the Playwright web server before `react-router dev`.
 */
import { generateKeyPairSync } from "node:crypto";
import { rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { getAddressDecoder } from "@solana/kit";

const here = dirname(fileURLToPath(import.meta.url));
const { privateKey, publicKey } = generateKeyPairSync("ed25519");
const secret = privateKey.export({ format: "der", type: "pkcs8" }).subarray(
	-32,
);
const pub = publicKey.export({ format: "der", type: "spki" }).subarray(-32);
const relayer = getAddressDecoder().decode(pub);

rmSync(resolve(here, "../.wrangler/e2e"), { recursive: true, force: true });
writeFileSync(
	resolve(here, ".dev.vars"),
	`# Generated by e2e/prepare.ts. Local Surfpool only.\nRELAYER_SECRET_KEY=${
		JSON.stringify([...secret, ...pub])
	}\n`,
);

const response = await fetch("http://127.0.0.1:8898/faucet", {
	method: "POST",
	headers: { "Content-Type": "application/json" },
	body: JSON.stringify({ address: relayer }),
});

if (!response.ok) {
	throw new Error(`faucet refused the relayer: ${response.status}`);
}

console.log(`e2e relayer ${relayer}`);
