/**
 * Prepare the end-to-end Worker against the running local Surfpool:
 *
 * - a fresh throwaway relayer keypair, funded from the faucet;
 * - the Introductory Exclusive Lootbox NFT collection, created and published
 *   by a fresh admin against the real Bubblegum V2 and Core programs;
 * - `e2e/.dev.vars` with both, and a clean D1.
 *
 * Run by the Playwright web server before the Worker starts.
 */
import { LootboxClient } from "@pina-rs/lootbox";
import {
	createSolanaRpc,
	generateKeyPairSigner,
	getAddressDecoder,
} from "@solana/kit";
import { generateKeyPairSync } from "node:crypto";
import { rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { clusterTime } from "../app/lib/clock.ts";
import { ensureCollection, planCollection } from "../scripts/collection.ts";

const CONTROL = "http://127.0.0.1:8898";
const here = dirname(fileURLToPath(import.meta.url));

async function faucet(address: string): Promise<void> {
	const response = await fetch(`${CONTROL}/faucet`, {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ address }),
	});

	if (!response.ok) {
		throw new Error(`faucet refused ${address}: ${response.status}`);
	}
}

const config: unknown = await (await fetch(`${CONTROL}/config`)).json();
const rpcUrl = Reflect.get(config as object, "rpcUrl");

if (
	typeof rpcUrl !== "string" ||
	Reflect.get(config as object, "metaplex") !== true
) {
	throw new Error(
		"Start the playground with real Metaplex programs: LOOTBOX_METAPLEX_PROGRAMS_DIR=target/deploy/metaplex pnpm playground:rpc (after fetch:metaplex-programs)",
	);
}

const { privateKey, publicKey } = generateKeyPairSync("ed25519");
const secret = privateKey.export({ format: "der", type: "pkcs8" }).subarray(
	-32,
);
const pub = publicKey.export({ format: "der", type: "spki" }).subarray(-32);
const relayer = getAddressDecoder().decode(pub);

await faucet(relayer);

const admin = await generateKeyPairSigner();

await faucet(admin.address);

const client = new LootboxClient(rpcUrl, admin);
const now = BigInt(await clusterTime(createSolanaRpc(rpcUrl)));
const plan = await planCollection(client, {
	origin: "https://lootbox.so",
	attachOpensAt: now - 60n,
	attachClosesAt: now + 60n * 86_400n,
});
const collection = await ensureCollection(client, plan);

rmSync(resolve(here, "../.wrangler/e2e"), { recursive: true, force: true });
writeFileSync(
	resolve(here, ".dev.vars"),
	[
		"# Generated by e2e/prepare.ts. Local Surfpool only.",
		`RELAYER_SECRET_KEY=${JSON.stringify([...secret, ...pub])}`,
		`EXCLUSIVE_COLLECTION_LOCALNET=${collection}`,
		"",
	].join("\n"),
);

console.log(`e2e relayer ${relayer}, Exclusive collection ${collection}`);
