[package]
name = "lootbox-program-cpi"
version.workspace = true
edition.workspace = true
publish = false
repository = "https://github.com/pina-rs/lootbox/tree/main/programs/lootbox_program/clients/cpi/lootbox_program"
description = "Generated CPI helpers for the Pina Lootbox program"
license.workspace = true
homepage.workspace = true

[dependencies]
pina = { workspace = true }
