[package]
name = "lootbox_program"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
repository = "https://github.com/pina-rs/lootbox/tree/main/programs/lootbox_program"
description = "A fully collateralized random-reward primitive for Solana"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []
bpf-entrypoint = []

[dependencies]
pina = { workspace = true, features = ["account-resize", "logs", "token"] }
solana-sha256-hasher = { workspace = true, features = ["sha2"] }
switchboard_randomness_cpi = { workspace = true }

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
